LOGDIR: "./logging"
DATASETS:
    3DPW: '../3DPW'
NUM_REQUIRED_KPS: 8
#SMPL:
#    SMPL_NEUTRAL: "../SMPL/models/basicmodel_neutral_lbs_10_207_0_v1.1.0.pkl"
#    SMPL_MALE: "../SMPL/models/basicmodel_m_lbs_10_207_0_v1.1.0.pkl"
#    SMPL_FEMALE: "../SMPL/models/basicmodel_f_lbs_10_207_0_v1.1.0.pkl"
DATA_SMPL: 
    JOINT_REGRESSOR_TRAIN_EXTRA: 'data/J_regressor_extra.npy'
    J_REGRESSOR_H36M_correct: 'data/J_regressor_h36m_correct.npy'
TRAIN:
    BATCH_SIZE_TRN: 16
    BATCH_SIZE_VAL: 16
    NUM_EPOCHS: 5
    LEARNING_RATE: 1.0e-4
MODEL:
    DIM_Z: 128
    ENCODER: 'resnet50'
LOSS:
    loss_smpl: 0
    loss_verts: 1.



    
    